// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxo2vVOVaN2iJNvqs9byHauW3wKoTyHMA',
    appId: '1:163884047687:web:d4acaecdec892a4503c062',
    messagingSenderId: '163884047687',
    projectId: 're-source-1c2a1',
    authDomain: 're-source-1c2a1.firebaseapp.com',
    storageBucket: 're-source-1c2a1.firebasestorage.app',
    measurementId: 'G-RJ9TTGN7KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEjNRWyApT5MmuSJvN7eIvnUUR-0rPh3w',
    appId: '1:163884047687:android:1e1233b73463ec2f03c062',
    messagingSenderId: '163884047687',
    projectId: 're-source-1c2a1',
    storageBucket: 're-source-1c2a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAjcZn_rVRaoSOVMrScKZ9DruVu9KKwSg',
    appId: '1:163884047687:ios:b455ef37dce436cf03c062',
    messagingSenderId: '163884047687',
    projectId: 're-source-1c2a1',
    storageBucket: 're-source-1c2a1.firebasestorage.app',
    iosBundleId: 'com.example.reSource',
  );
}
